# Generated by Django 4.1 on 2022-08-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio_project_name_alter_bio_profession_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('estimated_budget', models.CharField(max_length=50)),
                ('enter_your_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('B', 'Basic'), ('S', 'Standard'), ('P', 'Premium')], max_length=1)),
                ('price', models.IntegerField()),
                ('graphic_design', models.BooleanField(default=False)),
                ('web_design', models.BooleanField(default=False)),
                ('html_css', models.BooleanField(default=False)),
                ('ui_ux_design', models.BooleanField(default=False)),
                ('SEO_optimization', models.BooleanField(default=False)),
                ('business_development', models.BooleanField(default=False)),
            ],
        ),
    ]
