# Generated by Django 4.1 on 2022-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='myinfo',
            old_name='about_use',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='business_development',
            new_name='interface_design',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='graphic_design',
            new_name='motion_graphic',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='html_css',
            new_name='web_development',
        ),
        migrations.AlterField(
            model_name='bio',
            name='profession_category',
            field=models.CharField(choices=[('E', 'Education'), ('W', 'Work History'), ('P', 'Programming Skill'), ('D', 'Designer Skills'), ('S', 'SEO Skills')], default='E', max_length=30),
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='features',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_category',
            field=models.CharField(choices=[('A', 'All Work'), ('I', 'Illustration'), ('AN', 'Animation'), ('AP', 'App UI'), ('W', 'Web UI'), ('S', 'Social Media'), ('P', 'Print Design')], default='A', max_length=30),
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='ProfessionCategory',
        ),
        migrations.AddField(
            model_name='myinfo',
            name='features',
            field=models.ManyToManyField(to='home.features'),
        ),
    ]
