# Generated by Django 4.1 on 2022-08-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_portfolio_portfolio_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactUsModel',
        ),
    ]
